name: "Docs / Publish docs.scylladb.com/manual"

env:
  FLAG: manual

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up env
        run:  |
          cd submodules/scylladb/docs
          git show-ref
          make FLAG="${{ env.FLAG }}" setupenv

      - name: Build docs
        run: |
          cd submodules/scylladb/docs
          make FLAG="${{ env.FLAG }}" multiversion
          
      - name: Build redirects
        run: |
          cd submodules/scylladb/docs
          make FLAG="${{ env.FLAG }}" redirects

      - name: Deploy docs to GitHub Pages
        run: ./scripts/deploy_manual.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
